Engineering2
MIDO-ruby7/mokumoku pull request #2
Opened 2023-04-24 06:53 UTC by MIDO-ruby7

<img width="550" alt="スクリーンショット 2023-04-24 15 36 16" src="https://user-images.githubusercontent.com/111557292/233920524-cf282003-a3fb-4adb-a06d-a578abb8630f.png">

[x]ユーザー登録時に手入力やチェックボックス入力ではなく、セレクト形式で性別登録できる。
[x]イベント作成画面にOnly womanのチェックボックスにチェックを入れるだけで女性限定イベントを作できる。
[x]ユーザーが女性以外の場合、イベント作成時にOnly womanは表示されず、女性限定イベントが作成できない。
もくもく]女性限定イベントには女性のみが参加できる。
[x]女性以外の場合、女性限定イベントの詳細ページを開いた際に「このもくもく会に参加する」が表示されない。
[x]女性限定イベントは一覧・詳細画面にて「女性限定」が表記される。
【注意点】

[x]イベントが女性限定であるかを判定するカラムは"only_woman"とする
[x]ユーザーの性別登録のカラムは"gender"とする
[x]ユーザー登録時の性別のセレクト部分はenumを使って「その他・男性・女性」が表示される（その際に特に操作が無かれば"その他"が選択される）
[x]【Gemfile】
Testグループに以下のgemを追加

gem 'capybara', '~> 3.23'
gem 'selenium-webdriver'
gem 'webdrivers'
Gemfileの最下部に以下のgemを追加
gem 'nokogiri', '1.12.5'

2023-04-24 10:35 UTC, busitora requested changes
一点、ご確認お願いします！

2023-04-24 10:35 UTC, busitora commented on app/views/events/show.html.erb
> +                  <% else current_user.man? && current_user.other?  && events.only_woman? %>
モデルメソッドによせて単体テストを追加してください！

2023-04-25 08:44 UTC, MIDO-ruby7 commented
下記のように変更しました
app/views/events/show.html.erbのご指摘部分をevent.rbに```man_or_other?(current_user)```として定義
viewsで使用するためコントローラに@current_user_man_or_other を定義
viewsから呼び出し
<img width="564" alt="スクリーンショット 2023-04-25 17 37 04" src="https://user-images.githubusercontent.com/111557292/234223468-6e8484b9-66be-4d2c-8aac-257dea4fe07f.png">


懸念点として、
・そもそも、ご指摘を正しく汲み取れているか
・デコレータでなくモデルに定義してもよいのか
・単体テストを追加といういはモデルスペックを追加するということなのか
を疑問に思っております。見当違いのことをしている可能性があるため一度提出させていただきます。よろしくお願いします。

2023-04-25 12:11 UTC, enda1111 reviewed
> ・デコレータでなくモデルに定義してもよいのか

よいと思います。

> ・単体テストを追加といういはモデルスペックを追加するということなのか

そうですね、モデルスペック追加お願いします。

2023-04-25 12:11 UTC, enda1111 commented on app/models/event.rb
> +  def man_or_other?(current_user)
参加できるか？ を表すメソッド名がよいかなと思います。

2023-04-27 03:57 UTC, MIDO-ruby7 commented
ご指摘有難うございます。以下の変更を行いました。
・man_or_other?(current_user)メソッドをnon_woman_cannot_join?(current_user)に変更しました。
・event_spec.rbを追加し、non_woman_cannot_join?(current_user)に対するテストを追加しました。

<img width="485" alt="スクリーンショット 2023-04-27 12 54 31" src="https://user-images.githubusercontent.com/111557292/234755433-80934630-286b-4698-bbb5-90e3b8143704.png">

<img width="690" alt="スクリーンショット 2023-04-27 12 54 38" src="https://user-images.githubusercontent.com/111557292/234755466-38db904b-17e4-413d-8fa2-395c3e42f861.png">

2023-04-27 12:06 UTC, busitora commented
LGTM!お疲れ様でした！！

2023-04-27 16:51 UTC, merged